name: Docker Build Performance Test
on: [push, workflow_dispatch]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tmpfs: [enabled, disabled, enabled-default-size]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure Docker with tmpfs
        if: matrix.tmpfs == 'enabled'
        uses: ./
        with:
          size: '8G'
      - name: Configure Docker with tmpfs (default size)
        if: matrix.tmpfs == 'enabled-default-size'
        uses: ./
      - name: Configure Docker normal (baseline)
        if: matrix.tmpfs == 'disabled'
        run: |
          echo "Using default Docker configuration (disk-based)"
          docker info | grep "Docker Root Dir"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Start iostat monitoring
        run: |
          echo "=== Initial iostat snapshot ==="
          iostat -x 1 1
          echo "Starting continuous iostat monitoring..."
          iostat -x 10 > /tmp/iostat.log &
          echo $! > /tmp/iostat.pid
      - name: Build and load Docker image (with timing)
        uses: docker/build-push-action@v5
        with:
          context: ./example
          file: ./example/Dockerfile
          load: true
          tags: react-test-${{ github.run_id }}-${{ matrix.tmpfs }}:latest
      - name: Test the built image
        run: |
          echo "=== Build completed with tmpfs: ${{ matrix.tmpfs }} ==="
          docker images react-test-${{ github.run_id }}-${{ matrix.tmpfs }}:latest
          docker run --rm -d -p 3000:3000 --name react-app-${{ github.run_id }}-${{ matrix.tmpfs }} react-test-${{ github.run_id }}-${{ matrix.tmpfs }}:latest
          sleep 10
          curl -f http://localhost:3000 > /dev/null && echo "✅ App is running!" || echo "❌ App failed to start"
          docker stop react-app-${{ github.run_id }}-${{ matrix.tmpfs }}
      - name: Show system stats
        run: |
          echo "=== System stats for tmpfs: ${{ matrix.tmpfs }} ==="
          df -h
          free -h
          docker system df
      - name: Show iostat results
        run: |
          echo "=== Final iostat snapshot ==="
          iostat -x 1 1
          echo ""
          echo "=== Continuous iostat monitoring results ==="
          if [ -f /tmp/iostat.pid ]; then
            iostat_pid=$(cat /tmp/iostat.pid)
            kill $iostat_pid 2>/dev/null || true
            sleep 1
          fi
          if [ -f /tmp/iostat.log ]; then
            cat /tmp/iostat.log
          else
            echo "No iostat log found"
          fi
